#!/usr/bin/env groovy
library 'kibana-pipeline-library'

pipeline {
    agent { label 'docker && ubuntu-tests-l'}
    stages {
        stage('Run tests') {
            steps {
                sh 'kbn-alert-load run indicator-rules-index-size'
            }
        }
        stage('save artifacts') {
            steps {
                archiveArtifacts artifacts: '*.html'
            }
        }
    }
}