pipeline {
    agent any
    stages {
        stage('Run tests') {
            steps {
                sh 'kbn-alert-load run indicator-rules-index-size'
            }
        }
        stage('save artifacts') {
            steps {
                archiveArtifacts artifacts: '*.html'
            }
        }
    }
}